### PR TITLE
Add AccountService UpdateProfileImage

### PR DESCRIPTION
**Pull request by jyap808**
* POST to account/update_profile_image.json to set specified user profile image
* https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/post-account-update_profile_image

### CODE REVIEW

**Comment by dghubble** [comment]
Test please?

**Comment by jyap808** [comment]
Add a test case or test against the API?

**Comment by jyap808** [comment]
Added test case. Also confirming this was tested against the Twitter API and actually works.

**Comment by jyap808** [comment]
Mm, yeah on further testing with larger images (but within the 700kb documented limit) this doesn't work too well.

Errors: 
* 430 Request Header Fields Too Large
* stream error: stream ID 1; INTERNAL_ERROR; received from peer

Doesn't look to be documented properly on the Twitter API.

The test case image works fine though.

**Comment by jyap808** [comment]
@dghubble OK it works now with the latest commit.

**Comment by jyap808** [comment]
Not sure if you’re still testing but this isn’t merged to Main branch.

**Comment by dghubble** [comment]
Thanks, but the project is being deprecated https://github.com/dghubble/go-twitter/pull/207

**Pull request closed without merging**
