### PR TITLE
Support media upload

### PR DESCRIPTION
**Pull request by ahmedash95**
Hello, I added the required functions to upload media to twitter. I'll work on testing & simple refactoring during the next 2 days. feel free to merge it now since refactoring and updates can be in a sperate PRs

### CODE REVIEW

**Comment by drswork** [comment]
FWIW this looks like a subset of the functionality in PR #148

**Comment by ahmedash95** [comment]
> FWIW this looks like a subset of the functionality in PR #148

oh sorry didn't notice that PR. it's too bad that it didn't get merged till now

**Comment by x0rzkov** [comment]
Hi,

Hope you are all well !

Is it possible to add media while posting a tweet with your pull request ?

Cheers,
X

**Comment by ridwanakf** [comment]
Hi, can I use some of your code to make wrapper package to implement upload media for myself? Since I think the author has abandoned this project and I need that implementation for my app. 
Thank you very much.

**Comment by ahmedash95** [comment]
Hey @ridwanakf, Yes you can :) I'd be more than happy to see that my code would save you time.

**Comment by ahmedash95** [comment]
@x0rzkov sorry, but I'm not interested in this one anymore. please feel free to do any changes on my branch and make a new PR

**Pull request closed without merging**
