### PR TITLE
Support new Direct Message Events API

### PR DESCRIPTION
**Pull request by Xeoncross**
The existing API's for Direct Messages is being shut down on Aug 16st, 2018: https://twitter.com/TwitterDev/status/996783000741384192

This pull request is based on @listonb work in
https://github.com/dghubble/go-twitter/pull/87

No tests have been written for this single, new API call. However, before I spend anymore time on this I would like to see this discussed/approved/merged so I can continue to use the this great library.

### CODE REVIEW

**Comment by Xeoncross** [comment]
Going to work on features for optionally loading direct message sender / receiver information.

**Comment by Xeoncross** [comment]
The new Twitter API does not provide user information along with the Direct Message Events. I added a helper to load the account information as a map for easy use.

This PR provides the following API:

```
	// Initial Rest calls to the twitter events
	dms, _, err := client.DirectMessages.GetEvents(&twitter.DirectMessageEventsGetParams{Count: 3})
	if err != nil {
		log.Fatal(err)
	}

	// We also need the account screen_name for each sender/receiver
	var users map[int64]twitter.User
	users, err = dms.LoadAccounts(client)
	if err != nil {
		log.Fatal(err)
	}

	// fmt.Printf("%#v\n", dms)
	// fmt.Printf("%#v\n", users)

	for _, event := range dms.Events {
		m := event.Message
		fmt.Printf("DM: %s -> %s = %s\n",
			users[m.SenderID].ScreenName,
			users[m.Target.RecipientID].ScreenName,
			m.Data.Text,
		)
	}
```

**Comment by Xeoncross** [comment]
@dghubble I would like to see this PR merged as soon as possible. We are just over a month away from the shutdown of the current direct message API.

I tried to keep this PR as simple as possible. There are no changes to the existing codebase. Only a couple new structs and the new DM Events API call.

**Comment by Xeoncross** [comment]
@dghubble can you let me know what you're thinking? If you would like anything else added please let me know.

**Comment by djensen47** [comment]
When is this getting merged? The deadline was extended but it's better to get the changes in sooner and not wait until the last minute.

@Xeoncross Do you know of any other good golang libs for Twitter that are up to date with the API?

**Comment by Xeoncross** [comment]
@djensen47 the other [major libs](https://github.com/ChimeraCoder/anaconda) were missing the events API last I checked. The deadline is still Aug 16th, 2018 according to: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration

**Comment by dghubble** [comment]
Rebased and squashed as 306613eb8e78684a4c313e7f4398d35c7ff80d73 and fadf0839fb82dfc60b20a89fa89f9a14dedbb9c1 to show @listonb's efforts. Dropped the utility helper for hydrating user objects - those requiring similar functionality can write utilities suited for their use cases. Followup fixes to signatures and types in 1006667ae9713b4bc45a670d95ec5a3297313c3b.

**Comment by dghubble** [comment]
Merged now, had to wait on Travis a bit. Thanks for the patience.

**Pull request closed without merging**
