### PR TITLE
Feature/media upload

### PR DESCRIPTION
**Pull request by jlentink**
Add functionality to upload images to twitter to embed in tweet.

Example code:

```
	Ids := []int64{MediaId.MediaId}
	UpdateParams := &twitter.StatusUpdateParams{MediaIds: Ids};
	client.Statuses.Update("test", UpdateParams);
```

Added unit tests.

### CODE REVIEW

**Comment by jlentink** [comment]
@dghubble Sorry about the many 9 commits. I was figuring out Go on the go and the pull request was basically too early. It all should be fine now ;)

**Comment by lkramer** [comment]
Hi @jlentink, I'm sorry that it seems dghubble is a bit inactive at the moment, for what it's worth I forked this project just so that I could use your code.
One note: the documentation in the readme.md seems wrong when describing how chunk upload works.

**Comment by jlentink** [comment]
Let me have a look somewhere this week then I can update the code documentation for you.
Have fun with the code ;)

**Comment by dghubble** [comment]
I'd like to see this try to use https://github.com/jawher/sling.upload Much of this feels like re-inventing the file upload wheel.

**Comment by jlentink** [comment]
Awesome.
I was not aware of that piece of software i'll use it to rewrite it.

Met vriendelijke groet, Kind regards,

*Jason Lentink, **Technology Director Platforms & Big Builds*
LA · NY · BA · SP · LDN · *AMS* · STO · DXB · SG · SH
Call our Amsterdam office on +31356212150.
Reach me directly at +31611721201 or jason@mediamonks.com.

**Comment by dghubble** [comment]
This is a good shot. But as mentioned, I'd prefer to see an implementation that doesn't re-roll so much upload code. There are libraries that can do that part and I'm not keen to maintain that bit here or expand the scope if avoidable.

Looking forward to a potential revision.

**Pull request closed without merging**
