### PR TITLE
Add `Retweeters` support for retweeters ids

### PR DESCRIPTION
**Pull request by keaising**
Hi Dalton,

I have added a `Retweeters` to support [Statuses.Retweeters](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-retweeters-ids).
It contains `Retweeters` function in `statuses.go` to get user_ids which retweet specific tweet.
I have also added unit tests in the style of exist tests to test the functions.

It's my pleasure for your pulling.

Shuxiao.

### CODE REVIEW

**Comment by tomasnorre** [comment]
I would be really great to have this merged, needed this functionality for my Twitter bot.

**Comment by tomasnorre** [comment]
I can, by the way, verify that this works like a charm.

**Comment by Vanclief** [comment]
Surprised this has not been merged

**Comment by drswork** [comment]
I know it's been ages since you created this, but can I pull it into drswork/go-twitter?

**Comment by keaising** [comment]
> I know it's been ages since you created this, but can I pull it into drswork/go-twitter?

Of course, I hope you like it.

**Comment by tomasnorre** [comment]
> I know it's been ages since you created this, but can I pull it into drswork/go-twitter?

Just as an information I have used this fix, cherry-picked, for quite some time and never seen any issues with it.

**Comment by drswork** [comment]
Excellent! I'll patch this in over the weekend with a few more of the pending updates i have on my todo list. Thanks!

**Comment by drswork** [comment]
In and done, thanks.

**Comment by dghubble** [comment]
I've updated this:

* Fix endpoint from `retweeter/id.json` to `retweeters/id.json`
* Rename Retweeters to `RetweeterIDs` to be consistent with similar endpoint types (e.g. `FriendIDs`)
* Remove StringifyIDs field from StatusRetweeterParams. Users don't get to choose underlying types and when you don't set it, the ids are int64's not strings. Also its a boolean field, not a string
* Fix RetweeterIDs IDs type to be []int64 to align with Twitter default id type

**Pull request merged**
