### PR TITLE
Change Oauth2 example to use oauth2/clientcredentials

### PR DESCRIPTION
**Pull request by heavyengineer**
- The original example was too simple this version results in a working
client with just copy pasta
- Closes dghubble/go-twitter#88

### CODE REVIEW

**Comment by heavyengineer** [comment]
Meh, i don't know how i feel about this now. i've ended up going down a different road and feel that the original example might be clearer

**Comment by dghubble** [comment]
The original is better commented and makes it clear a plain token is expected (which one must go acquire). I think it could be nice to have the examples provide a bit of a helper with the two-legged clientcredentials helper like you show, but I dunno why the comments were removed? People look at these to get a sense of how it works.

**Comment by dghubble** [comment]
I've extended this PR's content with the other relevant examples in #144 Thanks!

**Comment by dghubble** [comment]
Merged as 5c87ef66d547a15731f1d5416dadf14e25f77383 :+1:

**Pull request closed without merging**
